version: '3.8'
services:
  dev-db:
    image: postgres:latest
    container_name: dev-db
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: bookmark
    networks:
      - bookmark
networks:
  bookmark: